package: jquery_file_upload
version: '1.0.0'
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/uploader'

page:
    title: 'jQuery File Upload'
    subpages:
        upload:
            title: 'Upload'
        endpoint:
            title: 'endpoint'
            hidden: true
            hasLayout: false
requires:
    redaxo: '>=5.0.0'

endpoint: '/redaxo/index.php?page=jquery_file_upload/endpoint'