package: uploader
version: '1.0.0'
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/uploader'

page:
    title: 'Uploader'
    icon: rex-icon rex-icon-import
    subpages:
        upload:
            title: 'Upload'
        endpoint:
            title: 'endpoint'
            hidden: true
            hasLayout: false
requires:
    redaxo: '>=5.0.0'

endpoint: '/redaxo/index.php?page=uploader/endpoint'
